name: Generate Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: manggalaputraaji
          template: classic
          
          # Hides the avatar, name, and join date header
          base: activity, community, repositories, metadata
          
          # Hides the "Last updated..." footer watermark
          config_output: svg
          config_padding: 0%
          config_timezone: Asia/Jakarta
          config_twemoji: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Hide footer notice
          config_display: regular
          plugin_lines: no
